### ISSUE TITLE
Ubuntu 16.04 : cassandra section needs an update.

### ISSUE THREAD

**Issue by indykish** [megamsys/docs.megam.io#23]
After installing cassandra, the following needs to be done.

```
export CQLSH_NO_BUNDLED=TRUE
pip install cassandra-driver
apt install python-pip
```

Also by moving to `habitat` we can cut down this stuff.

**Comment by rajesh-rajagopal** [comment]
This is not needed on latest Version on Cassandra...

We installed Cassandra 3.9 on customer server. Its running smoothly.
